bash_shell_net/urls.py
from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.static import static
# Uncomment the next two lines to enable the admin:
from django.contrib import admin
from django.urls import path, re_path
from django.views.generic import TemplateView

from wagtail.admin import urls as wagtailadmin_urls
from wagtail.contrib.sitemaps.views import sitemap
from wagtail.core import urls as wagtail_urls
from wagtail.documents import urls as wagtaildocs_urls

from .feeds import BlogFeedRss
from .sitemaps import BlogSitemap, ProjectSiteMap, ProjectsSiteMap

admin.autodiscover()

sitemaps = {'blog': BlogSitemap, 'project': ProjectSiteMap, 'projects': ProjectsSiteMap}

urlpatterns = [
    re_path(r'^cms/', include(wagtailadmin_urls)),
    re_path(r'^documents/', include(wagtaildocs_urls)),
    # re_path(r'^pages/', include(wagtail_urls)),
    url(r'^admin/doc/', include('django.contrib.admindocs.urls')),
    path('admin/', admin.site.urls),
    url(r'^sitemap\.xml$', sitemap, {
        'sitemaps': sitemaps,
    }),
    url(r'^feeds/rss/', BlogFeedRss()),
    url(r'^about/$', TemplateView.as_view(template_name="about.html"), name="about"),
    url(r'^opensource/$', TemplateView.as_view(template_name="open_source.html"), name="opensource"),
    # url(r'^oldblog/', include('blog.urls')),
    url(r'^archives/', include('blog.urls')),
    url(r'^projects/', include('projects.urls')),
    url(r'^', include(wagtail_urls)),
    # url(r'^', include('blog.urls')), # legacy stuff
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    # legacy url.
    # url(r'^archive/$', views.PostArchiveView.as_view(), name='blog_post_archive'),
    url(r'^$', views.PostArchiveView.as_view(), name='blog_post_archive'),
    # url(r'^(?P<year>\d{4})/(?P<month>[a-z]{3})/(?P<day>\w{1,2})/(?P<slug>[-\w]+)/$',
    #     views.PostDetailView.as_view(), name='legacy_post_detail'),
    # url(r'^preview/(?P<slug>[\w_-]+)/$', views.PostPreviewView.as_view(), name='blog_post_preview'),
    # url(r'^(?P<slug>[\w_-]+)/$', views.PostDetailView.as_view(), name='blog_post_detail'),
    # url(r'^$', views.PostListView.as_view(), name='blog_post_list'),
]

projects/urls.py
from __future__ import unicode_literals, absolute_import
from django.conf.urls  import *

from .import views


urlpatterns = [
    url(r'^(?P<slug>.+)/$', views.ProjectDetailView.as_view(), name='projects_project_detail'),
    url(r'^$', views.ProjectListView.as_view(), name='projects_project_list'),
]

projects/models.py
from django.db import models
from django.urls import reverse
from django.utils.text import slugify


class HostingService(models.Model):
    """Places that do project and code hosting"""
    name = models.CharField(max_length=50)
    url = models.URLField(max_length=100, blank=True)
    icon = models.ImageField(upload_to='projects/hostimages/', blank=True)

    # lib or django app for api calls/integration?

    class Meta:
        ordering = ('name', )

    def __str__(self):
        return self.name


class Language(models.Model):
    """
    A programming language
    """

    name = models.CharField(max_length=50, unique=True)
    description = models.TextField()

    class Meta:
        ordering = ('name', )

    def __str__(self):
        return self.name


class Project(models.Model):
    """
    A software development project
    """
    name = models.CharField(max_length=50)
    description = models.TextField(blank=True,
                                   help_text='A description of the project, history, reason for existence, etc.')
    primary_language = models.ForeignKey('projects.Language', blank=True, null=True, default=None,
                                         on_delete=models.SET_NULL, related_name='projects')
    other_languages = models.ManyToManyField('projects.Language', blank=True, related_name='other_language_projects')
    created_date = models.DateTimeField(auto_now_add=True)
    modified_date = models.DateTimeField(auto_now=True)
    hosting_services = models.ManyToManyField(HostingService, blank=True, through='ProjectHostingService',
                                              help_text='Place the code or project may be hosted',
                                              related_name='projects')
    is_active = models.BooleanField(blank=True, default=False)
    slug = models.SlugField(blank=True, max_length=50, default='')

    class Meta:
        ordering = ('name', )

    def __str__(self):
        return self.name

    def save(self, *args, **kwargs):
        if not self.slug:
            # duplicate slugs are not properly dealt with anywhere!
            self.slug = slugify(self.name.lower().strip())

        super(Project, self).save(*args, **kwargs)

    def get_absolute_url(self):
        return reverse('projects_project_detail', args=[self.slug])


class ProjectHostingService(models.Model):
    """
    Where a project is hosted
    """

    class VersionControlSystems(object):
        GIT = 1
        MERCURIAL = 2
        SVN = 3
        CVS = 4

    VCS_CHOICES = (
        (VersionControlSystems.GIT, 'git'),
        (VersionControlSystems.MERCURIAL, 'Mercurial'),
        (VersionControlSystems.SVN, 'SVN'),
        (VersionControlSystems.CVS, 'CVS'),
    )

    project = models.ForeignKey('projects.Project', related_name='project_hosting_services', on_delete=models.CASCADE)
    hosting_service = models.ForeignKey('projects.HostingService', null=True, on_delete=models.SET_NULL, default=None,
                                        related_name='project_hosting_services')
    project_url = models.URLField(blank=True, help_text='The website URL for the project')
    public_vcs_uri = models.URLField(blank=True,
                                     help_text='The URI that can be used to clone, checkout, etc. the project')
    vcs = models.IntegerField(choices=VCS_CHOICES)

    class Meta:
        ordering = ('project', 'hosting_service')

    def __str__(self):
        return '%s: %s' % (self.project, self.hosting_service)


class ProjectNews(models.Model):
    """
    News/blog post related to a project
    """

    project = models.ForeignKey('projects.Project', related_name='project_news', on_delete=models.CASCADE)
    created_date = models.DateTimeField(auto_now_add=True)
    modified_date = models.DateTimeField(auto_now=True)
    title = models.CharField(max_length=100)
    content = models.TextField(blank=True)
    is_published = models.BooleanField(db_index=True, default=False, blank=True)

    class Meta:
        ordering = ('-created_date', )

    def __str__(self):
        return self.title


class VersionControlSystem(models.Model):
    name = models.CharField(max_length=25)

    class Meta:
        ordering = ('name', )

    def __str__(self):
        return self.name

projects/views.py
from __future__ import absolute_import, unicode_literals, division

from django.shortcuts import render
from django.views.generic import ListView, DetailView

from .models import Project, ProjectNews


class ProjectListView(ListView):
    """
    Public list of projects
    """

    model = Project
    queryset = Project.objects.filter(is_active=True).order_by('primary_language__name', 'name')
    template_name = 'projects/projects_list.html'


class ProjectDetailView(DetailView):
    model = Project
    queryset = Project.objects.filter(is_active=True)
    template_name = 'projects/project_detail.html'

    def get_context_data(self, **kwargs):
        context = super(ProjectDetailView, self).get_context_data(**kwargs)
        context.update({
            'project_news': self.object.project_news.filter(is_published=True).order_by('-created_date')
        })

        return context

bash_shell_net/templates/projects/project_detail.html
{% extends 'base.html' %}
{% load blog_tags %}
{% block primary %}
  <div class="row">
    <div class="col-sm-12 project_detail__nav_row">
      <ul class="nav nav-tabs" role="tablist">
        <li class="nav-item"><a id="info-tab" class="nav-link active" href="#info-content" data-toggle="tab" role="tabpanel" aria-controls="info-content">Info</a></li>
        <li class="nav-item"><a id="news-tab" class="nav-link" href="#news-content" data-toggle="tab" role="tabpanel" aria-control="news-content">News</a></li>
      </ul>
    </div>
    <div class="col-sm-12 project_detail__content">
      <div class="tab-content col-sm-8 float-left">
        <div class="tab-pane active" id="info-content" role="tabpanel" aria-controlled-by="info-tab">
          {{ object.description|render_markdown|safe }}
        </div>
        <div class="tab-pane" id="news-content" role="tabpanel" aria-controlled-by="news-tab">
          <dl>
    				{% for news in project_news %}
    					<dt>{{ news.date_created }}</dt>
    					<dd>{{ news.content|render_markdown|safe }}</dd>
    				{% empty %}
    					<dd>Nothing to see here, move along.</dd>
    				{% endfor %}
          </dl>
        </div>
      </div>
      <div class="col-12 col-md-4 float-right">
        <div class="card">
          <div class="card-body">
            <h2 class="card-title">{{ object.name }}</h2>
            <div class="card-text">
              <dl class="dl-horizontal">
        				<dt><span >Created:</span></dt><dd>{{ project.created_date|date:"M d, Y" }}</dd>
        				<dt><span >Page updated:</span></dt><dd>{{ project.modified_date|date:"M d, Y" }}</dd>
        				<dt><span >Latest News:</span></dt><dd>{% if project_news.count > 0 %}{{ project_news.0.date_created|date:"M d, Y" }}{% endif %}</dd>
              </dl>

              {% if object.project_hosting_services.all.exists %}
            	    <p>View this project on:</p>
              	  <p>
          					{% for host in project.project_hosting_services.all %}
          						{# this all ends up on one line when output by the browser #}
          						<a href="{{ host.project_url|default:'#' }}">{{ host.hosting_service.name }}</a>
          						{% if host.public_vcs_uri and host.vcs %} {% if host.project_url %} - {% endif %}
          							<a href="{{ host.public_vcs_uri }}">{{ host.get_vcs_display }}</a>
          						{% endif %}<br />
          					{% endfor %}
                	</p>
              {% endif %}
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
{% endblock %}

bash_shell_net/templates/projects/projects_list.html
{% extends 'base.html' %}
{% block primary %}
<div class="page-header">
  <h2>Projects</h2>
</div>
  {% regroup object_list by primary_language as languages %}
    {% for language in languages %}
      <div id="{{ language.grouper }}" class="blog-post">
        <h3>{{ language.grouper }}</h3>
        <ul>
          {% for project in language.list %}
            <li><a href="{{ project.get_absolute_url }}">{{ project.name }}</a></li>
    	    {% endfor %}
    	  </ul>
      </div>
    {% endfor %}
{% endblock %}