bash_shell_net/urls.py
from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.static import static
# Uncomment the next two lines to enable the admin:
from django.contrib import admin
from django.urls import path, re_path
from django.views.generic import TemplateView

from wagtail.admin import urls as wagtailadmin_urls
from wagtail.contrib.sitemaps.views import sitemap
from wagtail.core import urls as wagtail_urls
from wagtail.documents import urls as wagtaildocs_urls

from .feeds import BlogFeedRss
from .sitemaps import BlogSitemap, ProjectSiteMap, ProjectsSiteMap

admin.autodiscover()

sitemaps = {'blog': BlogSitemap, 'project': ProjectSiteMap, 'projects': ProjectsSiteMap}

urlpatterns = [
    re_path(r'^cms/', include(wagtailadmin_urls)),
    re_path(r'^documents/', include(wagtaildocs_urls)),
    # re_path(r'^pages/', include(wagtail_urls)),
    url(r'^admin/doc/', include('django.contrib.admindocs.urls')),
    path('admin/', admin.site.urls),
    url(r'^sitemap\.xml$', sitemap, {
        'sitemaps': sitemaps,
    }),
    url(r'^feeds/rss/', BlogFeedRss()),
    url(r'^about/$', TemplateView.as_view(template_name="about.html"), name="about"),
    url(r'^opensource/$', TemplateView.as_view(template_name="open_source.html"), name="opensource"),
    # url(r'^oldblog/', include('blog.urls')),
    url(r'^archives/', include('blog.urls')),
    url(r'^projects/', include('projects.urls')),
    url(r'^', include(wagtail_urls)),
    # url(r'^', include('blog.urls')), # legacy stuff
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    # legacy url.
    # url(r'^archive/$', views.PostArchiveView.as_view(), name='blog_post_archive'),
    url(r'^$', views.PostArchiveView.as_view(), name='blog_post_archive'),
    # url(r'^(?P<year>\d{4})/(?P<month>[a-z]{3})/(?P<day>\w{1,2})/(?P<slug>[-\w]+)/$',
    #     views.PostDetailView.as_view(), name='legacy_post_detail'),
    # url(r'^preview/(?P<slug>[\w_-]+)/$', views.PostPreviewView.as_view(), name='blog_post_preview'),
    # url(r'^(?P<slug>[\w_-]+)/$', views.PostDetailView.as_view(), name='blog_post_detail'),
    # url(r'^$', views.PostListView.as_view(), name='blog_post_list'),
]

on_tap/models.py
from decimal import Decimal
from typing import List

from django.contrib.postgres.fields import CICharField
from django.core.paginator import EmptyPage, PageNotAnInteger, Paginator
from django.db import models
from django.db.models.query import QuerySet
from django.http import HttpRequest, HttpResponse
from django.utils import timezone

from modelcluster.fields import ParentalKey
from wagtail.admin.edit_handlers import (
    FieldPanel,
    FieldRowPanel,
    InlinePanel,
    MultiFieldPanel,
    PageChooserPanel,
    StreamFieldPanel,
)
from wagtail.contrib.routable_page.models import RoutablePageMixin, route
from wagtail.core.fields import RichTextField, StreamField
from wagtail.core.models import Orderable, Page
from wagtail.search import index
from wagtail.snippets.edit_handlers import SnippetChooserPanel
from wagtail.snippets.models import register_snippet
from wagtail_blocks.fields import STANDARD_STREAMFIELD_FIELDS


class RecipeHop(Orderable, models.Model):
    """
    A single amount of hops in a recipe
    """

    USE_STEP_CHOICES = (
        ('aroma', 'Aroma'),
        ('boil', 'Boil'),
        ('dryhop', 'Dry Hop'),
        ('firstwort', 'First Wort'),
        ('mash', 'Mash'),
    )

    FORM_CHOICES = (
        ('pellet', 'Pellet'),
        ('plug', 'Plug'),
        ('leaf', 'Leaf'),
    )

    TYPE_CHOICES = (
        ('bittering', 'Bittering'),
        ('aroma', 'Aroma'),
        ('both', 'Both'),
    )

    # Might FK this to a set of hops
    # would be good for name, type, substitutes, and origin
    recipe_page = ParentalKey(
        'on_tap.RecipePage', on_delete=models.CASCADE, related_name='hops', blank=False, null=False,
    )
    name = CICharField(max_length=100, blank=False)
    # A couple extra digits and decimal places to play it safe
    # Could also go FloatField and just be sure to round consistently
    alpha_acid_percent = models.DecimalField(max_digits=6, decimal_places=3, blank=False, null=False)
    amount = models.DecimalField(max_digits=6, decimal_places=2, blank=False, null=False)
    amount_units = models.CharField(max_length=5, choices=(('g', 'Grams'), ('oz', 'Ounces')))
    # use_step maps to BeerXML <USE>
    use_step = models.CharField(choices=USE_STEP_CHOICES, max_length=15, blank=False)
    use_time = models.IntegerField(
        blank=False, null=False, help_text='Time in minutes. Specific meaning varies by use type.'
    )
    notes = RichTextField(
        blank=True,
        default='',
        features=['superscript', 'subscript', 'strikethrough', 'bold', 'italic', 'ul', 'ol', 'link'],
    )

    # type = models.CharField(max_length=10, choices=TYPE_CHOICES)
    form = models.CharField(max_length=10, choices=FORM_CHOICES)
    beta_acid_percent = models.DecimalField(blank=True, default=None, max_digits=6, decimal_places=3, null=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    panels = [
        FieldPanel('name'),
        FieldPanel('alpha_acid_percent'),
        FieldPanel('amount'),
        FieldPanel('amount_units'),
        FieldPanel('form'),
        FieldPanel('use_step'),
        FieldPanel('use_time'),
        FieldPanel('notes'),
        FieldPanel('beta_acid_percent'),
    ]

    class Meta:
        # sort_order is on Orderable
        ordering = ('recipe_page', 'sort_order')

    def __str__(self) -> str:
        return self.name

    def weight_in_ounces(self) -> Decimal:
        if self.amount_units == 'g':
            return self.amount * Decimal('0.035274')
        # for now, must be oz
        return self.amount


class RecipeFermentable(Orderable, models.Model):
    """
    A fermentable such as a grain or malt extract used in a recipe

    The term "fermentable" encompasses all fermentable items that contribute substantially to the beer including
    extracts, grains, sugars, honey, fruits.
    """

    # TODO: usage? such as mash, vorlauf, or steep?

    UNIT_CHOICES = (
        ('g', 'Grams',),
        ('oz', 'Ounces'),
        ('kg', 'Kilograms'),
        ('lb', 'Pounds'),
    )

    TYPE_CHOICES = (
        ('grain', 'Grain'),
        ('dry_extract', 'Dry Extract'),
        ('liquid_extract', 'Liquid Extract'),
        ('sugar', 'Sugar'),
        ('adjunct', 'Adjunct'),
    )
    recipe_page = ParentalKey(
        'on_tap.RecipePage', on_delete=models.CASCADE, blank=False, null=False, related_name='fermentables',
    )
    amount = models.DecimalField(max_digits=6, decimal_places=3, blank=False, null=False)
    amount_units = models.CharField(max_length=5, blank=False, choices=UNIT_CHOICES,)
    # may add a static amount in kilograms to auto sort by amount
    notes = RichTextField(
        blank=True,
        default='',
        features=['superscript', 'subscript', 'strikethrough', 'bold', 'italic', 'ul', 'ol', 'link'],
    )

    # like hops, may be good FKd to a separate Fermentable with stats which don't change.
    # Name, Type, and Color belong on a separate Fermentable model, really.
    # there are many other stats which would be handy to keep on a separate model as well but are overkill here
    name = CICharField(max_length=100, blank=False)
    type = models.CharField(max_length=25, choices=TYPE_CHOICES, blank=False)
    color = models.DecimalField(
        max_digits=6,
        decimal_places=3,
        blank=True,
        null=True,
        default=None,  # assuming sugars may have no Lovibond or SRM value
        help_text='The color of the item in Lovibond Units (SRM for liquid extracts).',
    )
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    panels = [
        FieldPanel('name'),
        FieldPanel('amount'),
        FieldPanel('amount_units', heading='Units'),
        FieldPanel('color'),
        FieldPanel('type'),
        FieldPanel('notes'),
    ]

    class Meta:
        # sort_order is on Orderable
        ordering = ('recipe_page', 'sort_order')

    def __str__(self) -> str:
        return self.name

    def weight_in_pounds(self) -> Decimal:
        """
        Returns the weight in Pounds
        """
        # Keep it dumb and simple for now
        if self.amount_units == 'lb':
            return self.amount
        elif self.amount_units == 'kg':
            return self.amount * Decimal('2.20462262')
        elif self.amount_units == 'oz':
            return self.amount / Decimal('16.0')
        elif self.amount_units == 'g':
            # grams to kilograms then kilograms to pounds
            return (self.amount / Decimal('1000')) * Decimal('2.2042262')

    def calculate_mcu(self, gallons: Decimal) -> Decimal:
        """
        Calculate the Malt Color Units for use in Morey's equation to calculate beer SRM.

        MCU is the weight of the grain in (pounds * color lovibond) / gallons
        """
        if gallons <= Decimal('0'):
            raise ValueError('gallons must be a positive number greater than 0')
        # Ensuring we have gallons as Decimal
        return (self.weight_in_pounds() * self.color) / Decimal(gallons)


class RecipeYeast(Orderable, models.Model):
    """
    A yeast used in a recipe.

    The term "yeast" encompasses all yeasts, including dry yeast, liquid yeast and yeast starters.

    Like RecipeHop and RecipeFermentable - a good candidate to have an FK back to a base Yeast
    """

    UNIT_CHOICES = (
        ('', '---------'),
        ('Weight', (('g', 'Grams',), ('oz', 'Ounces'),),),
        ('Volume', (('tsp', 'Teaspoons'), ('tbsp', 'Tablespoons'), ('fl_oz', 'Fluid Oz'), ('l', 'Liters'),),),
    )

    YEAST_TYPE_CHOICES = (
        ('dry', 'Dry'),
        ('liquid', 'Liquid'),
    )
    recipe_page = ParentalKey(
        'on_tap.RecipePage', on_delete=models.CASCADE, related_name='yeasts', blank=False, null=False
    )
    # like hops, may be good FKd to a separate Fermentable with stats which don't change.
    # name and many other details which I am not storing now
    # would be handy to keep on a separate model as well but are overkill here
    name = CICharField(max_length=100, blank=False)
    amount = models.DecimalField(max_digits=6, decimal_places=3, blank=True, null=True, default=None)
    amount_units = models.CharField(max_length=5, choices=UNIT_CHOICES, blank=True, default='')
    notes = RichTextField(
        blank=True,
        default='',
        features=['superscript', 'subscript', 'strikethrough', 'bold', 'italic', 'ul', 'ol', 'link'],
    )
    add_to_secondary = models.BooleanField(blank=True, default=False, null=False)
    yeast_type = models.CharField(max_length=25, choices=YEAST_TYPE_CHOICES, blank=False)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        # sort_order is on Orderable
        ordering = ('recipe_page', 'sort_order')

    def amount_is_weight(self) -> bool:
        return amount_units in ['g', 'oz']

    def __str__(self) -> str:
        return self.name


class RecipeMiscIngredient(Orderable, models.Model):
    """
    The term "misc" encompasses all non-fermentable miscellaneous ingredients that are not hops or yeast and do not
    significantly change the gravity of the beer.  For example: spices, clarifying agents, water treatments, etc…

    Like RecipeHop and RecipeFermentable - a good candidate to have an FK back to a base Yeast
    """

    UNIT_CHOICES = (
        ('Weight', (('g', 'Grams'), ('oz', 'Ounces'), ('kg', 'Kilograms'), ('lb', 'Pounds'),),),
        (
            'Volume',
            (
                ('tsp', 'Teaspoons'),
                ('tbsp', 'Tablespoons'),
                ('fl_oz', 'Fluid Oz.'),
                # cups?
                ('l', 'Liters'),
                ('gal', 'Gallons'),
            ),
        ),
    )

    TYPE_CHOICES = (
        ('spice', 'Spice'),
        ('fining', 'Fining'),
        ('water_agent', 'Water Agent'),
        ('herb', 'Herb'),

on_tap/views.py
from django.shortcuts import render

# Create your views here.

bash_shell_net/templates/on_tap/on_tap.html
{% extends 'base.html' %}
{% load blog_tags wagtailcore_tags %}
{% block primary %}
  {% with page_title=page.title %}
    {{ block.super }}
  {% endwith %}
  <h3 class="mt-4">On Tap Now</h3>
  <div class="row mt-3">
    {% for batch in currently_on_tap %}
      <div class="col-12 col-md-4">
        <div class="card">
          <div class="card-header text-center">
            <div class="w-100"><a href="{% pageurl batch.recipe_page %}">{{ batch.recipe_page.name }}</a></div>
            <small>{{ batch.recipe_page.style.name }}{% if batch.recipe_page.style.bjcp_category %} ({{ batch.recipe_page.style.bjcp_category }}){% endif %}</small>
          </div>
          <div class="card-body">
            <p class="card-text">{{ batch.recipe_page.short_description }}</p>
            <p class="card-text">On Tap {{ batch.on_tap_date }}</p>
            <!-- <a href="{% pageurl batch.recipe_page %}" class="btn btn-primary">recipe</a> -->
          </div>
          <div class="card-footer">
            <a href="{% pageurl batch %}" class="card-link">Details</a>
          </div>
        </div>
      </div>
    {% endfor %}
  </div>

  {% if upcoming_batches is not None %}
    {% comment %}
      On further pages we just show the currently on tap and past batches for now.
      I might get fancy and paginate these lists and show both all the time with two separate page params.
    {% endcomment %}
    <h3 class="mt-4">Coming Soon</h3>
    <table class="table table-striped table-dark">
      <thead class="thead-dark">
        <tr>
          <th>Recipe Name</th>
          <th>Style</th>
          <th>Status</th>
          <th>Brewed Date</th>
          <th>Packaged Date</th>
          <th>On Tap Date</th>
        </tr>
      </thead>
      <tbody>
        {% for batch in upcoming_batches %}
          <tr>
            <td>
              <a href="{% pageurl batch.recipe_page %}">{{ batch.recipe_page.name }}</a>
              {% if batch.status != 'planned' %} (<a href="{% pageurl batch %}">Log</a>){% endif %}
            </td>
            <td>{{ batch.recipe_page.style }}</td>
            <td>{{ batch.get_status_display }}</td>
            <td>{{ batch.brewed_date }}</td>
            <td>{{ batch.packaged_date|default:"" }}</td>
            <td>{{ batch.on_tap_date|default:"" }}</td>
          </tr>
        {% endfor %}
      </tbody>
    </table>
  {% endif %}

  <h3 class="mt-4">Past Brews</h3>
  <table class="table table-striped table-dark">
    <thead class="thead-dark">
      <tr>
        <th>Recipe Name</th><th>Style</th><th>Status</th><th>Brewed Date</th><th>Packaged Date</th><th>On Tap Date</th>
      </tr>
    </thead>
    <tbody>
      {% for batch in past_batches %}
        <tr>
          <td><a href="{% pageurl batch.recipe_page %}">{{ batch.recipe_page.name }}</a> (<a href="{% pageurl batch %}">Log</a>)</td><td>{{ batch.recipe_page.style }}</td><td>{{ batch.get_status_display }}</td><td>{{ batch.brewed_date }}</td><td>{{ batch.packaged_date|default:"" }}</td><td>{{ batch.on_tap_date|default:"" }}</td>
        </tr>
      {% endfor %}
    </tbody>
  </table>
  <nav class="blog-pagination">
    <a class="btn btn-outline-primary {% if not page_obj.has_previous %}disabled{% endif %}" href="{% if page_obj.has_previous %}{% pageurl page %}?page={{ page_obj.previous_page_number }}{% else %}#{% endif %}">Newer Brews</a>
    <a class="btn btn-outline-primary {% if not page_obj.has_next %}disabled{% endif %}" href="{% if page_obj.has_next %}{% pageurl page %}?page={{ page_obj.next_page_number }}{% else %}#{% endif %}">Older Brews</a>
  </nav>
  <hr class="mt-4">
{% endblock primary %}

bash_shell_net/templates/on_tap/recipe_detail.html
{% extends 'base.html' %}
{% load wagtailcore_tags on_tap_tags %}
{% block page_stylesheets %}

  {% if page.style.color_min and page.style.color_max %}
    <style>
      {# extra specificity needed here or bootstrap padding values override this #}
      td.beer-style-guide__srm {
        padding: .5rem .75rem 0;
      }
      .beer-style-guide__srm-gradient {
        background-image: linear-gradient(to right, {{ page.style.color_min|floatformat:"0"|srm_to_hex }}, {{ page.style.color_max|floatformat:"0"|srm_to_hex }});
        padding: .25rem .75rem;
      }

      .recipe-stats__srm {
        background-color: {{ page.calculate_color_srm|floatformat:"0"|srm_to_hex }};
        padding: .25rem .75rem;
        {# When srm is less than 7-10, the white text gets hard to read #}
        {% if page.calculate_color_srm < 10 %}color: #2B3E50;{% endif %}
      }
    </style>
  {% endif %}
{% endblock page_stylesheets %}
{% block primary %}
  {% with page_title=page.title %}
    {{ block.super }}
  {% endwith %}
  <div class="blog-post">
    <div class="d-none d-lg-block col-md-3 col-lg-4 col-xl-4 float-right">
      <div class="card">
        <div class="card-header">
          Style Profile
        </div>
        <div class="card-body pb-0">
          <dl class="row mb-0">
            <div class="col-12 col-xl-6">
              <div class="row">
                <dt class="col-12">O.G.:</dt><dd class="col-12">{% if page.style.original_gravity_min and page.style.original_gravity_max %}{{ page.style.original_gravity_min|floatformat:"3" }} - {{ page.style.original_gravity_max|floatformat:"3" }}{% endif %}</dd>
              </div>
            </div>
            <div class="col-12 col-xl-6">
              <div class="row">
                <dt class="col-12">F.G.:</dt><dd class="col-12">{% if page.style.final_gravity_min and page.style.final_gravity_max %}{{ page.style.final_gravity_min|floatformat:"3" }} - {{ page.style.final_gravity_max|floatformat:"3" }}{% endif %}</dd>
              </div>
            </div>
            <div class="col-12 col-xl-6">
              <div class="row">
                <dt class="col-12">IBUs:</dt><dd class="col-12">{% if page.style.ibu_min and page.style.ibu_max %}{{ page.style.ibu_min|floatformat:"0" }} - {{ page.style.ibu_max|floatformat:"0" }}{% endif %}</dd>
              </div>
            </div>
            <div class="col-12 col-xl-6">
              <div class="row">
                <dt class="beer-style-guide__srm col-12">Color:</dt><dd class="col-12">{% if page.style.color_min and page.style.color_max %}<div class="text-center beer-style-guide__srm-gradient">{{ page.style.color_min|floatformat:"0" }} - {{ page.style.color_max|floatformat:"0" }} srm</div>{% endif %}</dd>
              </div>
            </div>
          </dl>
        </div>
      </div>

      <!-- recipe profile -->
      <div class="card mt-2">
        <div class="card-header">
          Recipe Statistics
        </div>
        <div class="card-body pb-0">
          <dl class="row mb-0">
            <div class="col-12 col-xl-6">
              <div class="row">
                <dt class="col-12">O.G.:</dt><dd class="col-12">{% if page.original_gravity %}{{ page.original_gravity|floatformat:"3" }}{% endif %}</dd>
              </div>
            </div>
            <div class="col-12 col-xl-6">
              <div class="row">
                <dt class="col-12">F.G.:</dt><dd class="col-12">{% if page.final_gravity %}{{ page.final_gravity|floatformat:"3" }}{% endif %}</dd>
              </div>
            </div>
            <div class="col-12 col-xl-6">
              <div class="row">
                <dt class="col-12">IBUs:</dt><dd class="col-12">{% if page.ibus_tinseth %}{{ page.ibus_tinseth|floatformat:"0" }}{% endif %}</dd>
              </div>
            </div>
            <div class="col-12 col-xl-6">
              <div class="row">
                <dt class="beer-style-guide__srm col-12">Color:</dt><dd class="col-12">{% if page.calculate_color_srm %}<div class="text-center recipe-stats__srm"">{{ page.calculate_color_srm|floatformat:"0" }} srm</div>{% endif %}</dd>
              </div>
            </div>
          </dl>
        </div>
      </div>
    </div>
    <div>
      <div class="recipe_detail__introduction">
        {{ page.introduction }}
      </div>
      <div class="col-12 d-lg-none">
        <div class="card row">
          <div class="card-header">
            Style Profile
          </div>
          <div class="card-body pb-0">
            <dl class="row mb-0">
              <div class="col-6">
                <div class="row">
                  <dt class="col-12">O.G.:</dt><dd class="col-12">{% if page.style.original_gravity_min and page.style.original_gravity_max %}{{ page.style.original_gravity_min|floatformat:"3" }} - {{ page.style.original_gravity_max|floatformat:"3" }}{% endif %}</dd>
                </div>
              </div>
              <div class="col-6">
                <div class="row">
                  <dt class="col-12">F.G.:</dt><dd class="col-12">{% if page.style.final_gravity_min and page.style.final_gravity_max %}{{ page.style.final_gravity_min|floatformat:"3" }} - {{ page.style.final_gravity_max|floatformat:"3" }}{% endif %}</dd>
                </div>
              </div>
              <div class="col-6">
                <div class="row">
                  <dt class="col-12">IBUs:</dt><dd class="col-12">{% if page.style.ibu_min and page.style.ibu_max %}{{ page.style.ibu_min|floatformat:"0" }} - {{ page.style.ibu_max|floatformat:"0" }}{% endif %}</dd>
                </div>
              </div>
              <div class="col-6">
                <div class="row">
                  <dt class="beer-style-guide__srm col-12">Color:</dt><dd class="col-12">{% if page.style.color_min and page.style.color_max %}<div class="text-center beer-style-guide__srm-gradient">{{ page.style.color_min|floatformat:"0" }} - {{ page.style.color_max|floatformat:"0" }} srm</div>{% endif %}</dd>
                </div>
              </div>
            </dl>
          </div>
        </div>
        <!-- recipe profile -->
        <div class="card row mt-2">
          <div class="card-header">
            Recipe Statistics
          </div>
          <div class="card-body pb-0">
            <dl class="row mb-0">
              <div class="col-6">
                <div class="row">
                  <dt class="col-12">O.G.:</dt><dd class="col-12">{% if page.original_gravity %}{{ page.original_gravity|floatformat:"3" }}{% endif %}</dd>
                </div>
              </div>
              <div class="col-6">
                <div class="row">
                  <dt class="col-12">F.G.:</dt><dd class="col-12">{% if page.final_gravity %}{{ page.final_gravity|floatformat:"3" }}{% endif %}</dd>
                </div>
              </div>
              <div class="col-6">
                <div class="row">
                  <dt class="col-12">IBUs:</dt><dd class="col-12">{% if page.ibus_tinseth %}{{ page.ibus_tinseth|floatformat:"0" }}{% endif %}</dd>
                </div>
              </div>
              <div class="col-6">
                <div class="row">
                  <dt class="beer-style-guide__srm col-12">Color:</dt><dd class="col-12">{% if page.calculate_color_srm %}<div class="text-center recipe-stats__srm"">{{ page.calculate_color_srm|floatformat:"0" }} srm</div>{% endif %}</dd>
                </div>
              </div>
            </dl>
          </div>
        </div>
      </div>
    </div>
    <span class="clearfix"></span>
    <div>
      <h2 name="recipe_details">{{ page.name }}</h2>
      <h4>{{ page.style }}</h4>
    </div>
    <table class="table mt-4">
      <thead class="table-active">
        <tr><th scope="col">Type</th><th scope="col">Boil Volume</th><th scope="col">Volume in Fermenter</th><th scope="col">Boil Time</th><th scope="col">Efficiency</th></tr>
      </thead>
      <tbody class="table-secondary">
        <tr>
          <td>{{ page.get_recipe_type_display }}</td>
          <td>{{ page.boil_size|floatformat:"2" }} {{ page.get_volume_units_display }}</td>
          <td>{{ page.batch_size|floatformat:"2" }} {{ page.get_volume_units_display }}</td>
          <td>{{ page.boil_time }} Minutes</td>
          <td>{{ page.efficiency }}%</td>
        </tr>
      </tbody>
    </table>
    <h5>Fermentables</h5>
    <table class="table">
      <thead class="table-active">
        <tr>
          <th>Name</th>
          <th>Amount</th>
          <th>Type</th>
          <th>Color</th>
        </tr>
      </thead>
      <tbody class="table-secondary">
      {% for fermentable in page.fermentables.all %}
        <tr>
          <td>{{ fermentable.name }}</td>
          <td>{{ fermentable.amount|floatformat:"2" }} {{ fermentable.amount_units }}</td>
          <td>{{ fermentable.get_type_display }}</td>
          <td>{{ fermentable.color|floatformat:"0" }} srm</td>
        <tr>
      {% endfor %}
      </tbody>
    </table>

    <h5>Hops</h5>
    <table class="table">
      <thead class="table-active">
        <tr>
          <th>Name</th>
          <th>Amount</th>
          <th>Form</th>
          <th>Step</th>
          <th>Time</th>
        </tr>
      </thead>
      <tbody class="table-secondary">
        {% for hop in page.hops.all %}
          <tr>
            <td>{{ hop.name }}</td>
            <td>{{ hop.amount|floatformat:"3" }} {{ hop.amount_units }}</td>
            <td>{{ hop.get_form_display }}</td>
            <td>{{ hop.get_use_step_display }}</td>
            <td>{{ hop.use_time }}</td>
          </tr>
        {% endfor %}
      </tbody>
    </table>

    <h5>Yeast</h5>
    <table class="table">
      <thead class="table-active">
        <tr>
          <th>Name</th>
          <th>Amount</th>
          <th>Type</th>
        </tr>
      </thead>
      <tbody class="table-secondary">
        {% for yeast in page.yeasts.all %}
          <tr>
            <td>{{ yeast }}</td>
            <td>{{ yeast.amount|floatformat:"3" }} {{ yeast.amount_units }}</td>
            <td>{{ yeast.get_yeast_type_display }}</td>
          </tr>
        {% endfor %}
      </tbody>
    </table>

    {% if page.miscellaneous_ingredients.exists %}
      <h5>Other Ingredients</h5>
      <table class="table">
        <thead class="table-active">
          <tr>
            <th>Name</th>
            <th>Amount</th>
            <th>Type</th>
            <th>Step</th>
            <th>Time</th>
          </tr>
        </thead>
        <tbody class="table-secondary">
          {% for misc in page.miscellaneous_ingredients.all %}
            <tr>
              <td>{{ misc.name }}</td>
              <td>{{ misc.amount|floatformat:"3" }} {{ hop.amount_units }}</td>
              <td>{{ misc.get_type_display }}</td>
              <td>{{ misc.get_use_step_display }}</td>
              <td>{{ misc.use_time }}</td>
            </tr>
          {% endfor %}
        </tbody>
      </table>
    {% endif %}
    <div class="recipe_detail__conclusion">
      {{ page.conclusion }}
    </div>
  </div>
{% endblock primary %}

bash_shell_net/templates/on_tap/style_detail.html
{% extends 'base.html' %}
{% load wagtailcore_tags %}

{% block 'primary' %}
  {{ page.title }}
  {{ page.author }}
  {% include_block page.body %}
{% endblock 'primary' %}